

#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdint.h>

#ifndef VENDOR_ID
#define VENDOR_ID 	0x0001
#endif

#ifndef PRODUCT_ID
#define PRODUCT_ID 	0x0001
#endif

enum usb_thing_cmd_e {
	USBTHING_CMD_NOP = 0x80,
	USBTHING_CMD_SERIAL_GET = 0x81,
	USBTHING_CMD_FIRMWARE_GET = 0x82,
	USBTHING_CMD_LED_SET = 0x91,
	USBTHING_CMD_GPIO_CFG = 0x92,
	USBTHING_CMD_GPIO_SET = 0x93,
	USBTHING_CMD_GPIO_GET = 0x94
};


/*****		 Protocol Configuration 		*****/
#define USBTHING_SERIAL_MAX_SIZE 		32
#define USBTHING_FIRMWARE_MAX_SIZE		32


#define USBTHING_CMD_NOP_SIZE 					0
#define USBTHING_CMD_SERIAL_GET_SIZE 			USBTHING_SERIAL_MAX_SIZE
#define USBTHING_CMD_FIRMWARE_GET_SIZE 			USBTHING_FIRMWARE_MAX_SIZE		
#define USBTHING_CMD_LED_SET_SIZE 				0

/*****		 GPIO Configuration messages 		*****/
#define USBTHING_CMD_GPIO_CFG_SIZE 				0
//Mode field
#define USBTHING_GPIO_CFG_MODE_SHIFT			(0)
#define USBTHING_GPIO_CFG_MODE_MASK				0x01
#define USBTHING_GPIO_CFG_MODE_INPUT 			(0 << USBTHING_GPIO_CFG_MODE_SHIFT)
#define USBTHING_GPIO_CFG_MODE_OUTPUT 			(1 << USBTHING_GPIO_CFG_MODE_SHIFT)
//Pull enable field
#define USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT 	(1)
#define USBTHIGN_GPIO_CFG_PULL_ENABLE_MASK 		(1 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)
#define USBTHING_GPIO_CFG_PULL_ENABLE	  		(0 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)
#define USBTHING_GPIO_CFG_PULL_DISABLE 	 		(1 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)
//Pull direction field
#define USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT 	(2)
#define USBTHIGN_GPIO_CFG_PULL_DIRECTION_MASK 	(1 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)
#define USBTHING_GPIO_CFG_PULL_LOW 				(0 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)
#define USBTHING_GPIO_CFG_PULL_HIGH 			(1 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)

#define USBTHING_CMD_GPIO_SET_SIZE 				0
#define USBTHING_CMD_GPIO_GET_SIZE				1


#endif
