

#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdint.h>

#ifndef VENDOR_ID
#define VENDOR_ID 	0x0001
#endif

#ifndef PRODUCT_ID
#define PRODUCT_ID 	0x0001
#endif

enum usb_thing_cmd_e {
	USBTHING_CMD_NOP = 0x80,
	USBTHING_CMD_SERIAL_GET = 0x81,
	USBTHING_CMD_FIRMWARE_GET = 0x82,
	USBTHING_CMD_LED_SET = 0x91,
	USBTHING_CMD_GPIO_CFG = 0x92,
	USBTHING_CMD_GPIO_SET = 0x93
};

#define USBTHING_GPIO_CFG_MODE_SHIFT			(0)
#define USBTHING_GPIO_CFG_MODE_MASK				0x01
#define USBTHING_GPIO_CFG_MODE_INPUT 			(0 << USBTHING_GPIO_CFG_MODE_SHIFT)
#define USBTHING_GPIO_CFG_MODE_OUTPUT 			(1 << USBTHING_GPIO_CFG_MODE_SHIFT)

#define USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT 	(1)
#define USBTHIGN_GPIO_CFG_PULL_ENABLE_MASK 		(1 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)
#define USBTHING_GPIO_CFG_PULL_ENABLE	  		(0 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)
#define USBTHING_GPIO_CFG_PULL_DISABLE 	 		(1 << USBTHING_GPIO_CFG_PULL_ENABLE_SHIFT)

#define USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT 	(2)
#define USBTHIGN_GPIO_CFG_PULL_DIRECTION_MASK 	(1 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)
#define USBTHING_GPIO_CFG_PULL_LOW 				(0 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)
#define USBTHING_GPIO_CFG_PULL_HIGH 			(1 << USBTHING_GPIO_CFG_PULL_DIRECTION_SHIFT)

enum gpio_pull_mode_e {
	GPIO_PULL_MODE_OFF = 0,
	GPIO_PULL_MODE_PULL_UP = 1,
	GPIO_PULL_MODE_PULL_DOWN = 2
};

struct gpio_config_s {
	uint8_t mode : 1;
	uint8_t pull : 2;
} __attribute((packed));

#define USBTHING_SERIAL_MAX_SIZE 		16
#define USBTHING_FIRMWARE_MAX_SIZE		16

#endif
